In [2]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Converting raw data into dataframe
dataset = pd.read_csv('a1_RestaurantReviews_HistoricDump.tsv', delimiter = '\t', quoting = 3)

In [4]:
print(dataset)

                                                Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
895  I want to first say our server was great and w...      1
896                     The pizza selections are good.      1
897              I had strawberry tea, which was good.      1
898  Highly unprofessional and rude to a loyal patron!      0
899                       Overall, a great experience.      1

[900 rows x 2 columns]


In [31]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

def rep(review):
    review = re.sub('[^a-zA-Z]', ' ', review)
    review = review.lower()
    reviews = review.split()
    reviews = [stemmer.stem(x) for x in reviews if x not in stopwords.words('english')]
    review = ' '.join(reviews)
    return review

In [32]:
dataset['Review'] = dataset['Review'].apply(rep)

In [33]:
print(dataset)

                                                Review  Liked
0                                       wow love place      1
1                                           crust good      0
2                                   tasti textur nasti      0
3    stop late may bank holiday rick steve recommen...      1
4                              select menu great price      1
..                                                 ...    ...
895         want first say server great perfect servic      1
896                                  pizza select good      1
897                                strawberri tea good      1
898                 highli unprofess rude loyal patron      0
899                                  over great experi      1

[900 rows x 2 columns]


In [20]:
corpus = dataset['Review'].tolist()
corpus[:5]

['wow love place',
 'crust good',
 'tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price']

In [21]:
import sklearn

In [22]:
# Creating the Bag of Words model using CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(corpus).toarray()
y = dataset['Liked'].tolist()

In [23]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [24]:
#Fitting Naive Bayes to the Training set and predicted the test set results
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB(alpha=0.1)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [25]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix:\n",cm)

Confusion Matrix:
 [[ 89  35]
 [ 27 119]]


In [26]:
# Computed Accuracy , Precision and Recall
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
score1 = accuracy_score(y_test,y_pred)
score2 = precision_score(y_test,y_pred)
score3= recall_score(y_test,y_pred)
print("\n")
print("Accuracy is ",round(score1*100,2),"%")
print("Precision is ",round(score2,2))
print("Recall is ",round(score3,2))



Accuracy is  77.04 %
Precision is  0.77
Recall is  0.82


In [28]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB(alpha=0.8)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [29]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix:\n",cm)

Confusion Matrix:
 [[ 68  56]
 [ 21 125]]


In [30]:
# Accuracy, Precision and Recall
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
score1 = accuracy_score(y_test,y_pred)
score2 = precision_score(y_test,y_pred)
score3= recall_score(y_test,y_pred)
print("\n")
print("Accuracy is ",round(score1*100,2),"%")
print("Precision is ",round(score2,2))
print("Recall is ",round(score3,2))



Accuracy is  71.48 %
Precision is  0.69
Recall is  0.86


In [21]:
#Fitting Logistic Regression to the Training set and predicted the test set results
from sklearn import linear_model
classifier = linear_model.LogisticRegression(C=1.5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

LogisticRegression(C=1.5)

In [23]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix:\n",cm)

Confusion Matrix:
 [[ 87  37]
 [ 30 116]]


In [24]:
# Computed Accuracy ,Precision and Recall
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
score1 = accuracy_score(y_test,y_pred)
score2 = precision_score(y_test,y_pred)
score3= recall_score(y_test,y_pred)
print("\n")
print("Accuracy is ",round(score1*100,2),"%")
print("Precision is ",round(score2,2))
print("Recall is ",round(score3,2))



Accuracy is  75.19 %
Precision is  0.76
Recall is  0.79
